# Please provide Atlas API credentials and Organization
atlas:
  create: false
  existingSecretName: ""
  orgId: "<Atlas Organization ID>"
  publicApiKey: "<Atlas_api_public_key>"
  privateApiKey: "<Atlas_api_private_key>"

  connectionSecretName: ""

project:
  create: false
  name: my-project
  atlasProjectName: "Test Project"
  annotations:
    {}
    # mongodb.com/atlas-resource-policy: keep
  # fullnameOverride: ""

  projectIpAccessList:
    - ipAddress: "0.0.0.0/1"
      comment: "REMOVE ME"

clusters: []
users: []
