mongodb-atlas-operator:
  enabled: true

# Please provide Atlas API credentials and Organization
atlas:
  create: false
  existingSecretName: ""
  connectionSecretName: ""

project:
  create: false
  name: my-project
  atlasProjectName: "Test Project"
  annotations:
    mongodb.com/atlas-resource-policy: keep
  # fullnameOverride: ""

  projectIpAccessList:
    - ipAddress: "0.0.0.0/1"
      comment: "REMOVE ME"

clusters: [] 
users: [] 
